particle minecraft:campfire_smoke_particle ~-5 ~ ~-2
particle minecraft:campfire_smoke_particle ~-5 ~ ~-1
particle minecraft:campfire_smoke_particle ~-5 ~ ~0
particle minecraft:campfire_smoke_particle ~-5 ~ ~1
particle minecraft:campfire_smoke_particle ~-5 ~ ~2
particle minecraft:campfire_smoke_particle ~-4 ~ ~-3
particle minecraft:campfire_smoke_particle ~-4 ~ ~-2
particle minecraft:campfire_smoke_particle ~-4 ~ ~-1
particle minecraft:campfire_smoke_particle ~-4 ~ ~0
particle minecraft:campfire_smoke_particle ~-4 ~ ~1
particle minecraft:campfire_smoke_particle ~-4 ~ ~2
particle minecraft:campfire_smoke_particle ~-4 ~ ~3
particle minecraft:campfire_smoke_particle ~-3 ~ ~-4
particle minecraft:campfire_smoke_particle ~-3 ~ ~-3
particle minecraft:campfire_smoke_particle ~-3 ~ ~-2
particle minecraft:campfire_smoke_particle ~-3 ~ ~-1
particle minecraft:campfire_smoke_particle ~-3 ~ ~0
particle minecraft:campfire_smoke_particle ~-3 ~ ~1
particle minecraft:campfire_smoke_particle ~-3 ~ ~2
particle minecraft:campfire_smoke_particle ~-3 ~ ~3
particle minecraft:campfire_smoke_particle ~-3 ~ ~4
particle minecraft:campfire_smoke_particle ~-2 ~ ~-5
particle minecraft:campfire_smoke_particle ~-2 ~ ~-4
particle minecraft:campfire_smoke_particle ~-2 ~ ~-3
particle minecraft:campfire_smoke_particle ~-2 ~ ~-2
particle minecraft:campfire_smoke_particle ~-2 ~ ~-1
particle minecraft:campfire_smoke_particle ~-2 ~ ~0
particle minecraft:campfire_smoke_particle ~-2 ~ ~1
particle minecraft:campfire_smoke_particle ~-2 ~ ~2
particle minecraft:campfire_smoke_particle ~-2 ~ ~3
particle minecraft:campfire_smoke_particle ~-2 ~ ~4
particle minecraft:campfire_smoke_particle ~-2 ~ ~5
particle minecraft:campfire_smoke_particle ~-1 ~ ~-5
particle minecraft:campfire_smoke_particle ~-1 ~ ~-4
particle minecraft:campfire_smoke_particle ~-1 ~ ~-3
particle minecraft:campfire_smoke_particle ~-1 ~ ~-2
particle minecraft:campfire_smoke_particle ~-1 ~ ~-1
particle minecraft:campfire_smoke_particle ~-1 ~ ~0
particle minecraft:campfire_smoke_particle ~-1 ~ ~1
particle minecraft:campfire_smoke_particle ~-1 ~ ~2
particle minecraft:campfire_smoke_particle ~-1 ~ ~3
particle minecraft:campfire_smoke_particle ~-1 ~ ~4
particle minecraft:campfire_smoke_particle ~-1 ~ ~5
particle minecraft:campfire_smoke_particle ~0 ~ ~-5
particle minecraft:campfire_smoke_particle ~0 ~ ~-4
particle minecraft:campfire_smoke_particle ~0 ~ ~-3
particle minecraft:campfire_smoke_particle ~0 ~ ~-2
particle minecraft:campfire_smoke_particle ~0 ~ ~-1
particle minecraft:campfire_smoke_particle ~0 ~ ~0
particle minecraft:campfire_smoke_particle ~0 ~ ~1
particle minecraft:campfire_smoke_particle ~0 ~ ~2
particle minecraft:campfire_smoke_particle ~0 ~ ~3
particle minecraft:campfire_smoke_particle ~0 ~ ~4
particle minecraft:campfire_smoke_particle ~0 ~ ~5
particle minecraft:campfire_smoke_particle ~1 ~ ~-5
particle minecraft:campfire_smoke_particle ~1 ~ ~-4
particle minecraft:campfire_smoke_particle ~1 ~ ~-3
particle minecraft:campfire_smoke_particle ~1 ~ ~-2
particle minecraft:campfire_smoke_particle ~1 ~ ~-1
particle minecraft:campfire_smoke_particle ~1 ~ ~0
particle minecraft:campfire_smoke_particle ~1 ~ ~1
particle minecraft:campfire_smoke_particle ~1 ~ ~2
particle minecraft:campfire_smoke_particle ~1 ~ ~3
particle minecraft:campfire_smoke_particle ~1 ~ ~4
particle minecraft:campfire_smoke_particle ~1 ~ ~5
particle minecraft:campfire_smoke_particle ~2 ~ ~-5
particle minecraft:campfire_smoke_particle ~2 ~ ~-4
particle minecraft:campfire_smoke_particle ~2 ~ ~-3
particle minecraft:campfire_smoke_particle ~2 ~ ~-2
particle minecraft:campfire_smoke_particle ~2 ~ ~-1
particle minecraft:campfire_smoke_particle ~2 ~ ~0
particle minecraft:campfire_smoke_particle ~2 ~ ~1
particle minecraft:campfire_smoke_particle ~2 ~ ~2
particle minecraft:campfire_smoke_particle ~2 ~ ~3
particle minecraft:campfire_smoke_particle ~2 ~ ~4
particle minecraft:campfire_smoke_particle ~2 ~ ~5
particle minecraft:campfire_smoke_particle ~3 ~ ~-4
particle minecraft:campfire_smoke_particle ~3 ~ ~-3
particle minecraft:campfire_smoke_particle ~3 ~ ~-2
particle minecraft:campfire_smoke_particle ~3 ~ ~-1
particle minecraft:campfire_smoke_particle ~3 ~ ~0
particle minecraft:campfire_smoke_particle ~3 ~ ~1
particle minecraft:campfire_smoke_particle ~3 ~ ~2
particle minecraft:campfire_smoke_particle ~3 ~ ~3
particle minecraft:campfire_smoke_particle ~3 ~ ~4
particle minecraft:campfire_smoke_particle ~4 ~ ~-3
particle minecraft:campfire_smoke_particle ~4 ~ ~-2
particle minecraft:campfire_smoke_particle ~4 ~ ~-1
particle minecraft:campfire_smoke_particle ~4 ~ ~0
particle minecraft:campfire_smoke_particle ~4 ~ ~1
particle minecraft:campfire_smoke_particle ~4 ~ ~2
particle minecraft:campfire_smoke_particle ~4 ~ ~3
particle minecraft:campfire_smoke_particle ~5 ~ ~-2
particle minecraft:campfire_smoke_particle ~5 ~ ~-1
particle minecraft:campfire_smoke_particle ~5 ~ ~0
particle minecraft:campfire_smoke_particle ~5 ~ ~1
particle minecraft:campfire_smoke_particle ~5 ~ ~2